name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor # includes patch updates
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE_GH_TOKEN }}
