name: auto-merge

on: [pull_request_target]

jobs:
  auto-merge:
    name: auto-merge
    runs-on: ubuntu-latest
    # Guarantee that commit comes from Dependabot (don't blindly trust external GitHub Actions)
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor # includes patch updates
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE_GH_TOKEN }}
